gpu_num: [0, 1, 2]
random_seed: 0

#model
model:
  lr: 0.00001
  batch_size: 1
  epochs: 1
  bert_model: allenai/longformer-base-4096
  optimizer: adamw
  gradient_clip: 1
  gradient_accumulation: 4


# data and model path
data:
  training_set: data/train.jsonl
  dev_set: data/dev.jsonl
  test_set: data/test.jsonl


full_doc: true
model_path: /cs/labs/tomhope/forer11/SciCo_Retrivel/LLaMA-2-7B-32K
log: /cs/labs/tomhope/forer11/SciCo_Retrivel/logs

# definition extraction
definition_extraction: False
should_save_definition: False

from_gpt: False


# inference
checkpoint_multiclass: /cs/labs/tomhope/forer11/SciCo_Retrivel/LLaMA-2-7B-32K/multiclass/version_60/checkpoints/epoch=0-step=35550.ckpt
checkpoint_coref: path-to-binary-coref-ckpt
checkpoint_hypernym: path-hierarchy-model-ckpt
agg_threshold: 0.6  # for agglomerative clustering
hypernym_threshold: 0.5 # for hypernym scores
save_path: /cs/labs/tomhope/forer11/SciCo_Retrivel/LLaMA-2-7B-32K
